### ISSUE TITLE
Annotation is not working (Solved)

### ISSUE THREAD

**Issue by nordfalk** [adrianwalker/multiline-string#2]
Hello,

I think this is not working in Java 7 or 8.
At least I fail to get the HTML comment into the line.

Could you make a statement on whether this still works?

**Comment by adrianwalker** [comment]
Hi

I've just updated the dependency version on the multiline-string-usage project and tested on Java 8.  It works for me, please make sure you're using version 0.2.0, as version 0.1.0 contained @SupportedSourceVersion(SourceVersion.RELEASE_6) which prevented it working on later versions of Java.

Cheers

Adrian

**Comment by nordfalk** [comment]
Thanks, yes it seems its working from maven and doing:
java -cp ~/.m2/repository/org/adrianwalker/multiline-string-usage/0.2.0/multiline-string-usage-0.2.0.jar org.adrianwalker.multilinestring.MultilineStringUsage

For some reason it doesent work from Netbeans (ant-based project), neither when I
A) copy the source code and include tools.jar
or
B) use ~/.m2/repository/org/adrianwalker/multiline-string/0.2.0/multiline-string-0.2.0.jar as a library in my project

In both cases your test code
```
  /**
  <html>
    <head/>
    <body>
      <p>
        Hello<br/>
        Multiline<br/>
        World<br/>
      </p>
    </body>
  </html>
  */
  @Multiline
  private static String html;

  public static void main(final String[] args) {
    System.out.println(html);
  }

```
just prints null out.

**Comment by adrianwalker** [comment]
That sounds like the annotation processor isn't being used at compile time.  I've been running this from Netbeans using Maven so I'm not sure about Ant, it's been a while since I used it.

Could you use the Ant javac task's compilerarg to pass the '-processor' option to javac?

e.g. 
<pre>
&lt;javac ...>
  &lt;compilerarg line="-processor org.adrianwalker.multilinestring.MultilineProcessor" />
&lt;/javac>
</pre>
http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javac.html#processing

**Comment by adrianwalker** [comment]
Or could you specify the annotation processor via the NetBeans GUI?

![image](https://cloud.githubusercontent.com/assets/4210902/24841107/dffd0094-1d73-11e7-8f71-03b3d6cb88fc.png)

**Comment by nordfalk** [comment]
That's probably the cause. 
Thank you. 

Perhaps you could put a note about this in a readme file (and link to this discussion).
In the meantime I suggest you keep this bug as 'open' so people that cannot get it to work will quickly see what they forgot to do.

**Comment by vpogrebi** [comment]
I cannot find multiline-string.0.2.0.jar in Maven repository (it only contains 0.1.1 and 0.1.2). Where can it be downloaded from (which global repository)?

Can you upload 0.2.0 and 0.2.1 to Maven repo?

**Comment by vpogrebi** [comment]
I have this issue using Eclipse (using multiline-string.0.1.2.jar). In the editor, string value is visible (when hovering cursor over the variable). But at run-time (either 'Run' or 'Debug') - these values are always null. Executing Java class (compiled by Eclipse) in the shell (terminal) - shows same outcome (null values).

I tried all of the above suggestions (setting project's Annotation Processor, adding command-line argument) - nothing works. 

When compiling code "by hand" in the terminal, I do see compiler incompatibility warning

`warning: No SupportedSourceVersion annotation found on org.adrianwalker.multilinestring.MultilineProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.adrianwalker.multilinestring.MultilineProcessor' less than -source '1.8'
`

... but at least manually compiled code works.

So... I am not sure that multiline-string.0.2.0 is going to solve this issue with using it in Eclipse. It is rather some sort of project configuration issue that must be done in order to compile Java code (with multiline-string processor) correctly.

Please advise how this can be done in Eclipse.

P.S.    Tried using IntelliJ - same issue: runtime values are null

**Comment by adrianwalker** [comment]
Hi @vpogrebi

> I cannot find multiline-string.0.2.0.jar in Maven repository (it only contains 0.1.1 and 0.1.2). Where can it be downloaded from (which global repository)?
> 
> Can you upload 0.2.0 and 0.2.1 to Maven repo?

I have not uploaded this library to any publicly available repositories, and don't plan to, although I believe others have.  I would recommend you just build from source and install into your local and/or organisation's repository.

> I have this issue using Eclipse (using multiline-string.0.1.2.jar). In the editor, string value is visible (when hovering cursor over the variable). But at run-time (either 'Run' or 'Debug') - these values are always null. Executing Java class (compiled by Eclipse) in the shell (terminal) - shows same outcome (null values).
> 
> I tried all of the above suggestions (setting project's Annotation Processor, adding command-line argument) - nothing works.
> 

@benelog has put together some good wiki pages on how to use this library with Eclipse, with and without Maven:
https://github.com/benelog/multiline/wiki/Maven-project-with-Eclipse
https://github.com/benelog/multiline/wiki/Non-Maven-Java-project-with-Eclipse

> When compiling code "by hand" in the terminal, I do see compiler incompatibility warning
> 
> `warning: No SupportedSourceVersion annotation found on org.adrianwalker.multilinestring.MultilineProcessor, returning RELEASE_6. warning: Supported source version 'RELEASE_6' from annotation processor 'org.adrianwalker.multilinestring.MultilineProcessor' less than -source '1.8'`
> 
> ... but at least manually compiled code works.

This was fixed in commit 984ba3cc69e2a1b5a73b8d9dc092ae0adcbb863e by removing:

`@SupportedSourceVersion(SourceVersion.RELEASE_6)`

> 
> So... I am not sure that multiline-string.0.2.0 is going to solve this issue with using it in Eclipse. It is rather some sort of project configuration issue that must be done in order to compile Java code (with multiline-string processor) correctly.
> 
> Please advise how this can be done in Eclipse.
> 
> P.S. Tried using IntelliJ - same issue: runtime values are null

If you're compiling with Java version 9 or higher you might be interested in this post:

http://www.adrianwalker.org/2018/08/java-910-multiline-string.html

**Comment by adrianwalker** [comment]
Hi again @vpogrebi, just a another thought - it's worth noting that @benelog's fork includes additional MultilineProcessor classes for issues he encountered with Eclipse:

https://github.com/benelog/multiline/tree/master/multiline-string/src/main/java/org/adrianwalker/multilinestring

I've not pulled these additions into the original code base because I'm not an Eclipse user.  You might have better luck with his fork.

**Comment by vpogrebi** [comment]
Thank you,

I still have two comments/issues:

1. Main point suggested in @benelog's blog (https://github.com/benelog/multiline/wiki/Non-Maven-Java-project-with-Eclipse) - is to compile Java code outside of Eclipse:

> Compile on the command line
> 
> Include 'multiline-string-0.1.2.jar' in the '-classpath' option.
> 
> javac -classpath multiline-string-0.1.2.jar Hello.java 

... while my question was - how to make that work "all within Eclipse" (without resorting to go outside of the IDE)

2. I did not find any JAR distribution(s) of @benelog's multiline-string fork. It must be a "published" JAR distribution through one of the global repositories (Maven, Jcenter/Bintray, etc.) - to allow automated downloads by build scripts (Maven, Gradle, etc.). I did find that Bintray has a "placeholder" for it (https://bintray.com/benelog/maven/multiline) - but there are no JAR downloads available
